import re

from .date_constants import LICHOIS_DATE_FORMAT, LICHOIS_DATETIME_FORMAT
from .date_constants import LICHOIS_SHORT_DATE_FORMAT, LICHOIS_SHORT_DATETIME_FORMAT


MALE = "male"
FEMALE = "female"
OTHER = "other"

YES = "Yes"
NO = "No"
NOT_APPLICABLE = "N/A"

# Status Constants
OPEN = "open"
CLOSED = "closed"
DRAFT = "draft"
PENDING = "pending"
APPROVED = "approved"
ACCEPTED = "accepted"
REJECTED = "rejected"
CANCELLED = "cancelled"
SCHEDULED = "scheduled"
ON_GOING = "on_going"
COMPLETED = "completed"
DEFERRED = "deferred"
STARTED = "started"
ENDED = "ended"
PRESENT = "present"
ABSENT = "absent"
ACTIVE = "active"
INACTIVE = "inactive"

# Document Status
ISSUED = "issued"
NOT_ISSUED = "not_issued"
LOST = "lost"
STOLEN = "stolen"
DAMAGED = "damaged"

# Communication Methods
EMAIL = "email"
SMS = "sms"
POSTAL = "postal"
TELEPHONE = "telephone"
CELLPHONE = "cellphone"

# Address Type Constants
RESIDENTIAL = "residential"
BUSINESS = "business"
POSTAL = "postal"
PRIVATE = "private"

# Identity Types
OMANG = "OMANG"
PASSPORT = "PASSPORT"
DRIVERS_LICENSE = "DRIVERS"
PASSPORT = "PASSPORT"
OMANG_RECEIPT = "OMANG_RCPT"
OTHER_ID = "OTHER"

# Marital Status
SINGLE = "single"
MARRIED = "married"
WIDOWED = "widowed"
SEPARATED = "separated"
DIVORCED = "divorced"

# Permit Types
WORK = "work"
RESIDENCE = "residence"

# Person Types
APPLICANT = "applicant"
MOTHER = "mother"
FATHER = "father"
CHILD = "child"
GUARDIAN = "guardian"
SPONSOR = "sponsor"
WITNESS = "witness"
DECLARANT = "declarant"
ADOPTIVE_PARENT = "adoptive_parent"
SUBSCRIBER = "subscriber"
EMPLOYEE = "employee"
INVESTOR = "investor"
OFFICER = "officer"
DEPENDENT = "dependent"
VOLUNTEER = "volunteer"
STUDENT = "student"
IMMIGRANT = "immigrant"
MISSIONARY = "missionary"

# Education Levels
HIGH_SCHOOL = "high_school"
ASSOCIATE_DEGREE = "associate_degree"
BACHELORS_DEGREE = "bachelors_degree"
MASTERS_DEGREE = "masters_degree"
DOCTORATE = "doctorate"
DIPLOMA = "diploma"
CERTIFICATE = "certificate"
VOCATIONAL = "vocational"
PROFESSIONAL_DEGREE = "professional_degree"
TECHNICAL_DEGREE = "technical_degree"
POSTGRADUATE_CERTIFICATE = "postgraduate_certificate"
OTHER_EDUCATION = "Other"

# Duration Types
YEARS = "years"
MONTHS = "months"
WEEKS = "weeks"
DAYS = "days"
PERMANENT = "permanent"
EMERGENCY_SHORT = "short"
EMERGENCY_MEDIUM = "medium"
EMERGENCY_LONG = "long"

# Application Types
INITIAL = "initial"
RENEWAL = "renewal"
REPLACEMENT = "replacement"
APPEAL = "appeal"
CANCELLATION = "cancellation"
REVIEW = "review"
RECONSIDERATION = "reconsideration"

# Visa Type Constants
DIPLOMATIC = "diplomatic"
OFFICIAL = "official"
EMPLOYMENT = "employment"
BUSINESS = "business"
INVESTMENT = "investment"
TOURIST = "tourist"
VISITOR = "visitor"
STUDY = "study"
TRANSIT = "transit"
EMERGENCY = "emergency"


UUID_PATTERN = re.compile(
    '[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}|'
    '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}')
VIEW = 'VIEW'
WEEKDAYS = 'weekdays'
WEEKENDS = 'weekends'
ANYTIME = "anytime"


# EDC constants
ABNORMAL = "ABNORMAL"
ABSENT = "absent"
ADDITIONAL = True
AFTERNOON = "afternoon"
ALIVE = "alive"
ALWAYS = "always"
ANONYMOUS = "anonymous"
ANYTIME = "anytime"
AWAITING_RESULTS = "awaiting_results"
BLACK = "black"
BOTH = "both"
BY_BIRTH = "BY_BIRTH"
CANCELLED = "cancelled"
CHOL = "chol"
CLINIC = "clinic"
CLINICAL_ENDPOINT = "clinical_endpoint"
CLINICAL_WITHDRAWAL = "clinical_withdrawal"
CLINICIAN = "clinician"
CLOSED = "closed"
COLLATERAL_HISTORY = "collateral_history"
COMPLETE = "COMPLETE"
COMMUNITY = "community"
CONFIRMED = "confirmed"
CONSENTED = "consented"
CONTINUOUS = "continuous"
CONTROL = "control"
CREATE = "CREATE"
DEAD = "dead"
DECEASED = "dead"
DECLINED = "Declined"
DECREASED = "decreased"
DEFAULTED = "defaulted"
DEFAULTER = "defaulter"
DELETE = "DELETE"
DELIVERY = "delivery"
DIABETES = "diabetes"
DIVORCED = "divorced"
DM = "dm"
DONE = "done"
DONT_KNOW = "dont_know"
DWTA = "DWTA"  # don't want to answer
ERROR = "ERROR"
ESTIMATED = "estimated"
EVENING = "evening"
FAILED_ELIGIBILITY = "failed eligibility"
FALSE = "false"
FASTING = "fasting"
FEEDBACK = "feedback"
FEMALE = "F"
FORMER_SMOKER = "former_smoker"
FREE_OF_CHARGE = "free"
FUTURE_DATE = "future_date"
HEADACHE = "headache"
HELD = "held"
HIDE_FORM = "NOT_REQUIRED"
HIGH = "high"
HIGH_PRIORITY = "high"
HIV = "HIV"
HOME = "home"
HOSPITAL = "hospital"
HOSPITALIZED = "hospitalized"
HOSPITAL_NOTES = "hospital_notes"
HOSPITAL_OR_CLINIC = "hospital_or_clinic"
HTN = "htn"
HYPERTENSION = "hypertension"
IGNORE = "ignore"
IN_PROGRESS = "in_progress"
INCOMPLETE = "INCOMPLETE"
IND = "IND"
INITIAL = "initial"
INPATIENT = "inpatient"
INSERT = "INSERT"
INSURANCE = "insurance"
INTEGRATED = "integrated"
INTEGRATED_CLINIC = "integrated_clinic"
INTERVENTION = "intervention"
INVESTIGATOR = "investigator"
INVESTIGATOR_DECISION = "investigator_decision"
IN_PERSON = "in_person"
IS_NULL = "is_null"
LAST_MONTH = "last_month"
LAST_WEEK = "last_week"
LIVE = "live"
LOW = "low"
LOW_PRIORITY = "low"
MALE = "M"
MALIGNANCY = "malignancy"
MARRIED = "married"
MEDIUM_PRIORITY = "medium"
MEASURED = "measured"
MICROSCOPY = "microscopy"
MOBILE_NUMBER = "mobile_no"
MODIFIED = "modified"
MONTHLY = "monthly"
MORNING = "morning"
MULTI_MORBIDITY = "multi"
NAIVE = "NAIVE"
NCD = "NCD"
NEG = "NEG"
NEVER = "NEVER"
NEW = "New"
NEW_FIELD = "new_field"
NEXT_OF_KIN = "next_of_kin"
NEXT_WEEK = "next_week"
NO = "No"
NONE = "none"
NONSMOKER = "nonsmoker"
NON_BLACK = "non_black"
NON_FASTING = "non_fasting"
NORMAL = "NORMAL"
NOT_ADDITIONAL = False
NOT_ANSWERED = "not_answered"
NOT_APPLICABLE = "N/A"
NOT_AVAILABLE = "not_available"
NOT_DONE = "not_done"
NOT_ESTIMATED = "not_estimated"
NOT_EVALUATED = "not_evaluated"
NOT_EXAMINED = "not_examined"
NOT_NULL = "not_null"
NOT_RECORDED = "not_recorded"
NOT_REQUIRED = "not_required"
NOT_SURE = "not_sure"
NOT_TESTED = "not_tested"
NO_EXAM = "NO_EXAM"
NO_UNCONFIRMED = "no_unconfirmed"
OBSERVATION = "observation"
OK = "OK"
OFF_STUDY = "off study"
OFF_STUDY_VISIT = "off study"
OMANG = "OMANG"
ON_ART = "on_art"
ON_STUDY = "on study"
ONGOING = "ongoing"
OPEN = "open"
OPTION_RETIRED = "OPTION_RETIRED"
OPTIONAL = True
PRIMARY = "primary"
PRINT = "PRINT"
PRIVATE = "private"
PURPOSIVELY_SELECTED = "purposively_selected"
QUERY = "QUERY"
QUESTION_RETIRED = "QUESTION_RETIRED"
RANDOM_SAMPLING = "random_sampling"
RAPID_TEST = "rapid_test"
RARELY = "rarely"
RECEIVED = "received"
REDUCED = "reduced"
REFILL = "refill"
REFUSED = "REFUSED"
RELATIVE = "relative"
RESOLVED = "resolved"
RESTARTED = "restarted"
ROUTINE_VISIT = "routine_visit"
SAE = "sae"
SCREENED = "SCREENED"
SECONDARY = "secondary"
SEQUENTIAL = "sequential"
SEROCONVERSION = "seroconversion"
SHOW_FORM = "NEW"
SINGLE = "single"
SMOKER = "smoker"
SOMETIMES = "sometimes"
STEROIDS = "steroids"
STOPPED = "stopped"
STUDY_DEFINED_TIMEPOINT = "study_defined_timepoint"
SUBJECT = "subject"
SYSTEMATIC = "systematic"
TBD = "tbd"  # to be determined
TELEPHONE = "telephone"
TERTIARY = "tertiary"
TEST = "test"
THIS_MONTH = "this_month"
THIS_WEEK = "this_week"
TIMEPOINT = "timepoint"
TODAY = "today"
TOMORROW = "tomorrow"
TOXICITY = "toxicity"
TRUE = "true"
TUBERCULOSIS = "TB"
UNK = "UNK"
UNKNOWN = "unknown"
UNWELL_VISIT = "unwell_visit"
UPDATE = "UPDATE"
VERY_OFTEN = "very_often"
VIEW = "VIEW"
VISUAL_LOSS = "visual_loss"
WARN = "warn"
WEEKDAYS = "weekdays"
WEEKENDS = "weekends"
WEEKLY = "weekly"
WIDOWED = "widowed"
YEARLY = "yearly"
YES = "Yes"
YESTERDAY = "yesterday"

# operators
EQ = "="
GT = ">"
GTE = ">="
LT = "<"
LTE = "<="

# days of the week
MONDAY = "monday"
TUESDAY = "tuesday"
WEDNESDAY = "wednesday"
THURSDAY = "thursday"
FRIDAY = "friday"
SATURDAY = "saturday"
SUNDAY = "sunday"